### PR TITLE
L5Kit documentation update

### PR DESCRIPTION
**Pull request by theDebugger811**
Topic: Updated the L5Kit Documentation.

Changes:
1. Re-organized the files into the folder 'docs' in the main folder.
2. Organized the sections in a hierarchical manner.
3. Adding the links to the CVPR 2021 Tutorial videos.
4. Converted all .md files to .rst for consistency.
5. Fixed broken links.
6. Improved formatting.

### CODE REVIEW

**Review by perone — APPROVED** [review]
Amazing work, thanks a lot @theDebugger811 !

**Comment by perone** [comment]
There are some warnings when I run: `sphinx-build ../docs ../docs_built`:

```
/home/ubuntu/code/l5kit/docs/API/modules.rst: WARNING: document isn't included in any toctree
```

Can you check ? There are other warnings as well.

**Comment by theDebugger811** [comment]
Thanks for the quick review @perone. 
Some warnings are a result of incorrect documentation, I am fixing that. 

However, there are multiple warnings of the same `more than one target found for cross-reference`. I assume they are harmless. If not, let me know what should be done. Thanks!

**Comment by perone** [comment]
For the cross-reference I would be worried if they are from main titles only. The most important issue was that the modules.rst wasn't included in any TOC also.

**Comment by theDebugger811** [comment]
@perone, I have fixed the docstring warnings. Let me know if I should go ahead with the merge. Thanks!

**Review by perone — APPROVED** [review]
Yes, let's merge this one.

**Pull request merged**
