### PR TITLE
Add Notebook for L5Kit Gym-compatible environment

### PR DESCRIPTION
**Pull request by theDebugger811**
Notebook to introduce and rollout gym environment

### CODE REVIEW

**Comment by theDebugger811** [comment]
Link to notebook in collab: https://colab.research.google.com/github/lyft/l5kit/blob/parth%2Fgym_notebook/examples/RL/gym_environment.ipynb

@perone , @lucabergamini

**Comment by theDebugger811** [comment]
Things I know left to do:
1. Add the link in L5Kit Docs
2. Add `gym_config.yaml` link in `setup_notebook_collab.sh`

**Comment by perone** [comment]
LGTM, I think you can add the `gym_config.yaml` in this PR and then the doc change in another one, as you will need the link for it too.

**Review by perone — APPROVED** [review]

**Comment by theDebugger811** [comment]
@perone I have added the link. Should I go ahead with the merge?

Also, should I remove 'create_gym_example.py' in this PR? (it is in examples/RL)

**Comment by perone** [comment]
Yes, please remove the old script as the content is the same and in the notebook it is more visual.

**Review by perone — APPROVED** [review]
Thanks @theDebugger811, make sure to adjust the title of this PR before squashing and merging it.

**Pull request merged**
