### PR TITLE
bugfix in yaw fitting

### PR DESCRIPTION
**Pull request by yawei-ye**
# Changes
* Bugfix in yaw residual compute, it should be wrapped

### CODE REVIEW

**Comment by yawei-ye** [comment]
PTAL @lucabergamini @perone

**Review by perone — DISMISSED** [review]

**Review by lucabergamini — APPROVED** [review]

**Review by perone — APPROVED** [review]
LGTM. Do you think it would be easy to add a test case to cover that issue ? If yes then I would say it would be nice to add, but if it would take too much data mocking to cover it then its ok.

**Comment by yawei-ye** [comment]
> LGTM. Do you think it would be easy to add a test case to cover that issue ? If yes then I would say it would be nice to add, but if it would take too much data mocking to cover it then its ok.

Good point, I created a JIRA ticket: https://jira.lyft.net/browse/AVSW-76244

**Comment by yawei-ye** [comment]
💨

**Pull request merged**
