### PR TITLE
allow rasterizer and returned image to be None

### PR DESCRIPTION
**Pull request by Jimexist**
I think currently if you use None rasterizer it'll throw.

### CODE REVIEW

**Comment by lucabergamini** [comment]
> I think currently if you use None rasterizer it'll throw.

yeah, the case with no rasterizer is currently not handled. I'm not sure this PR fixes it though. Can This be placed into a `DataLoader`?  Last time I've checked `None` was not something the default collate function was able to handle

**Comment by Jimexist** [comment]
> > I think currently if you use None rasterizer it'll throw.
> 
> yeah, the case with no rasterizer is currently not handled. I'm not sure this PR fixes it though. Can This be placed into a `DataLoader`? Last time I've checked `None` was not something the default collate function was able to handle

@lucabergamini updated, also if it is designed not to return none then I guess we can just use stub rasterizer in the absence of a rasterizer?

**Comment by lucabergamini** [comment]
> @lucabergamini updated, also if it is designed not to return none then I guess we can just use stub rasterizer in the absence of a rasterizer?

We have to make a choice:
1. when you pass None you don't get an image at all in the dict;
2. when you pass None a StubRasterizer is created and you get a black image;

I can see pros and cons in both, what do you think is better and why @Jimexist ?

1. nice because semantically you don't want an image, bad for consistency (but maybe only in tests)
2. nice for consistency but the field actually makes no sense

Another option would be to require a rasterizer always

**Comment by Jimexist** [comment]
> > @lucabergamini updated, also if it is designed not to return none then I guess we can just use stub rasterizer in the absence of a rasterizer?
> 
> We have to make a choice:
> 
> 1. when you pass None you don't get an image at all in the dict;
> 2. when you pass None a StubRasterizer is created and you get a black image;
> 
> I can see pros and cons in both, what do you think is better and why @Jimexist ?
> 
> 1. nice because semantically you don't want an image, bad for consistency (but maybe only in tests)
> 2. nice for consistency but the field actually makes no sense
> 
> Another option would be to require a rasterizer always

I'd prefer 1st option because users who explicitly pass in `None` for rasterizer would expect the image to be not there or at least can handle the discrepancy of returned items' keys; while if we silently use `StubRasterizer` there's a chance of misuse.

If we had to go with 2nd option, I'd suggest putting `torch.tensor(0.)` or even `torch.tensor(np.nan)` just so that it's not used by chance (and also saves memory).

**Comment by lucabergamini** [comment]
> I'd prefer 1st option because users who explicitly pass in `None` for rasterizer would expect the image to be not there or at least can handle the discrepancy of returned items' keys; while if we silently use `StubRasterizer` there's a chance of misuse

I agree, and as far as I can see it's what you've already implemented, so I'll approve it :)

**Review by lucabergamini — APPROVED** [review]
LGTM

**Comment by lucabergamini** [comment]
> I'd prefer 1st option because users who explicitly pass in `None` for rasterizer would expect the image to be not there or at least can handle the discrepancy of returned items' keys; while if we silently use `StubRasterizer` there's a chance of misuse

I agree, and as far as I can see it's what you've already implemented, so I'll approve it :)

**Pull request merged**
