### PR TITLE
add subpixel precision to BoxRasteriser

### PR DESCRIPTION
**Pull request by lucabergamini**
Add subpixel precision to BoxRasterizer also

Note:
 I had to remove the `LINE_AA` flag as it was making a test failing (and also resulting boxes had the corner cut)

### CODE REVIEW

**Comment by thomasbrandon** [comment]
From a quick experiment without `LINE_AA` you don't seem to get full subpixel rendering. It does at least round values not truncate as before so some improvement but not as with full subpixel rendering.
With `LINE_AA`:
SubPixel_AA

Without `LINE_AA`:
SubPixel_NoAA


Here's the [notebook](https://gist.github.com/thomasbrandon/060d85280240cdc7d7ea0b17ed36beab).

**Comment by lucabergamini** [comment]
> From a quick experiment without `LINE_AA` you don't seem to get full subpixel rendering

ok, let me check again this and try to fix that test then

**Comment by lucabergamini** [comment]
Last commit should address this @thomasbrandon

**Review by stefaniespeichert — APPROVED** [review]
lgtm

**Review by yye-lyft — APPROVED** [review]
LGTM

**Pull request merged**
