### PR TITLE
Lberg/refactor transform functions

### PR DESCRIPTION
**Pull request by lucabergamini**
Avoid Stacking and slicing. Add better docstring. Drop 4D points support.

### CODE REVIEW

**Comment by yye-lyft** [comment]
I implemented something similar using Tensor which avoid `transpose` the points, I would like to get ride of `transform_points_transposed `: https://github.com/lyft/avresearch/blob/yye/refactor-transform-libs/avresearch/data/transforms.py#L29

**Comment by lucabergamini** [comment]
> I would like to get rid of `transform_points_transposed`

Take a look at the function now @yye-lyft. If you're fine with that we can remove the transposed version

**Comment by yye-lyft** [comment]
> > I would like to get rid of `transform_points_transposed`
> 
> Take a look at the function now @yye-lyft. If you're fine with that we can remove the transposed version

Yeah, let's remove the transposed version

**Review by yye-lyft — DISMISSED** [review]
LGTM, nice work!

**Review by yye-lyft — APPROVED** [review]
LGTM

**Pull request merged**
