### PR TITLE
Update visualise_data.ipynb

### PR DESCRIPTION
**Pull request by piantic**
I found a typo.
So, I want to edit this.

visulisation -> visualisation

### CODE REVIEW

**Comment by lucabergamini** [comment]
Hi @piantic , can you sign the CLA? otherwise I can't merge this PR in master

**Comment by piantic** [comment]
Hi, @lucabergamini, sorry for late your comment.
I signed the CLA.
Could you merge this to original repo?

**Review by piantic — COMMENTED** [review]
CLA has been done.

**Review by lucabergamini — APPROVED** [review]
great, thanks for picking this up :)

**Comment by piantic** [comment]
Great! Thanks for adding this. :)

**Pull request merged**
